# Site
name: "Abdoulaye's Blog"
title: "Abdoulaye's Blog"
description: "Abdoulaye Binta Bah, software developer, data scientist, 
  business analyst, product manager and entrepreneur making the world a 
  better place using cutting edge technologies."
logo: 'assets/images/logo3.png'
favicon: 'assets/images/favicon.png'
baseurl: /blog
google_analytics: 'UA-46278016-1'
disqus: 'demowebsite'
#mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  abdoulaye:
    name: abdoulaye
    display_name: Abdoulaye Binta Bah
    gravatar: ec85e2770d349f7100ac634f9100a2fa
    email: bahabdoulayebinta@gmail.com
    web: https://www.wowthemes.net
    twitter: https://twitter.com/abdbintbah
    description: "This is the author box. Write a short description of the author here. You are currently previewing Mediumish demo, a Jekyll template compatible with Github pages."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
